// Generated by CoffeeScript 1.2.1-pre
var currentCuestion, currentQuiz, generateQuiz, loadQuiz, quizzes, resetQuiz, rightAnswers, validate, validateQuiz;

quizzes = {};

currentQuiz = [];

currentCuestion = 0;

rightAnswers = 0;

generateQuiz = function(quizName, quiz) {
  var elements, quizHTML;
  quizHTML = '';
  $(quiz).each(function(key, quizElement) {
    quizHTML += '<div id="quizElement' + key + '"><div class="question">' + quizElement.question + '</div>' + '<ol id="' + "question" + key + quizName + '" data-question-checked="false">';
    $(quizElement.options).each(function(key, optionText) {
      return quizHTML += '<li>' + optionText + '</li>';
    });
    return quizHTML += '</ol></div>';
  });
  $('#quizContainer').append(quizHTML);
  elements = $('#quizContainer').find(" ol li");
  elements.mousedown(function(event) {
    if (!$(this).parent().data("questionChecked")) {
      return $(this).toggleClass("selected");
    }
  });
  return elements.hover(function() {
    return $(this).addClass("activo");
  }, function() {
    return $(this).removeClass("activo");
  });
};

validate = function() {
  var correctAnswers, correctOptions, currentQuizElement, elements, evaluationMode, score;
  correctOptions = 0;
  currentQuizElement = currentQuiz[currentCuestion];
  correctAnswers = currentQuizElement.correctAnswers;
  evaluationMode = currentQuizElement.mode;
  score = 0;
  elements = $('#quizElement' + currentCuestion + ' li');
  if (elements.filter(".selected").length === 0) return;
  elements.each(function(index, Element) {
    if ($(this).hasClass("selected")) {
      if (correctAnswers.indexOf(index) > -1) {
        correctOptions += 1;
        return $(this).attr("class", "good");
      } else {
        return $(this).attr("class", "bad");
      }
    }
  });
  if (correctOptions !== correctAnswers.length) {
    if (evaluationMode === "permisive" && elements.filter(".bad").length === 0) {
      elements.filter(".good").attr("class", "almostGood");
      rightAnswers += Math.round(correctOptions * 10 / correctAnswers.length) / 10;
    }
  } else {
    rightAnswers += 1;
  }
  document.getElementById("txtAciertos").value = rightAnswers;
  return $('#quizElement' + currentCuestion + " ol").data("questionChecked", true);
};

validateQuiz = function() {
  var nQuestions, _results;
  nQuestions = currentQuiz.length;
  currentCuestion = 0;
  _results = [];
  while (currentCuestion < nQuestions) {
    validate();
    _results.push(currentCuestion += 1);
  }
  return _results;
};

resetQuiz = function() {
  rightAnswers = 0;
  document.getElementById("txtAciertos").value = rightAnswers;
  return $('#quizContainer').find(" ol li").attr("class", "");
};

loadQuiz = function(quizName) {
  var fileref;
  if (quizName === "-1") return;
  fileref = document.createElement('script');
  fileref.setAttribute("type", "text/javascript");
  fileref.setAttribute("src", "quizzes/" + quizName + ".json");
  document.getElementsByTagName("head")[0].appendChild(fileref);
  $("#quizContainer").empty();
  rightAnswers = 0;
  document.getElementById("txtAciertos").value = rightAnswers;
  resetQuiz();
  return window.setTimeout(function() {
    currentQuiz = quizzes[quizName];
    return generateQuiz(quizName, currentQuiz);
  }, 500);
};
